### PR TITLE
Matthews branch

### PR DESCRIPTION
**Pull request by matthemwoore**
Dumb question, but there are no issues with merging my branch which only adds a folder to the master, correct?

### CODE REVIEW

**Comment by romanjeff** [comment]
Should be fine. Merging is usually only a problem if there are conflicts and git should tell you about those.

**Comment by matthemwoore** [comment]
cool, thanks

**Comment by romanjeff** [comment]
I do think it might sense for either you or Drew to fork this entire repo over to a new one so that you don't need me as a reviewer on pull requests. Up to you guys, but I haven't really had the time to look at your commits nor do I have any context to know if they're any good or not, haha, so having me as a reviewer makes no sense.

**Comment by matthemwoore** [comment]
Oh I don't think we need you as a reviewer. I only selected that so you
would see my question. I can move the whole thing if you prefer. I'm going
to be committing stuff more often now, just so it's accessible to Drew or
whoever else; If it's notifying you each time, then that will probably get
annoying. It's up to you.

**Comment by matthemwoore** [comment]
For example, if you didn't just get a notification right now, then you
shouldn't expect to get (m)any in the future.

PS, I hope you're doing well!

**Pull request merged**
